// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"github.com/go-kratos/kratos/v2/log"
	"order-service/internal/biz/order_sync"
	"order-service/internal/conf"
	"order-service/internal/consumer"
)

// Injectors from wire.go:

// wireApp init kratos application.
func wireApp(data *conf.Data, confConsumer *conf.Consumer, consumer_Queue *conf.Consumer_Queue, logger log.Logger) (*consumer.OrderConsumer, func(), error) {
	iSyncOrderHandler := order_sync.NewSyncOrderHandler(logger)
	orderConsumer, err := consumer.NewOrderConsumer(confConsumer, iSyncOrderHandler, logger)
	if err != nil {
		return nil, nil, err
	}
	return orderConsumer, func() {
	}, nil
}
