// Code generated by mockery v2.46.0. DO NOT EDIT.

package mocks

import (
	context "context"

	mock "github.com/stretchr/testify/mock"
)

// PublisherInterface is an autogenerated mock type for the PublisherInterface type
type PublisherInterface struct {
	mock.Mock
}

// PublishOrderEvents provides a mock function with given fields: ctx, eventName, eventData, orderId
func (_m *PublisherInterface) PublishOrderEvents(ctx context.Context, eventName string, eventData string, orderId string) error {
	ret := _m.Called(ctx, eventName, eventData, orderId)

	if len(ret) == 0 {
		panic("no return value specified for PublishOrderEvents")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string, string, string) error); ok {
		r0 = rf(ctx, eventName, eventData, orderId)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// NewPublisherInterface creates a new instance of PublisherInterface. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewPublisherInterface(t interface {
	mock.TestingT
	Cleanup(func())
}) *PublisherInterface {
	mock := &PublisherInterface{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
