server:
  http:
    addr: 0.0.0.0:8000
    timeout: 1s
  grpc:
    addr: 0.0.0.0:9000
    timeout: 1s
data:
  database:
    driver: postgres
    source: "host=pg-master user=%s password=%s dbname=order_service port=5432 sslmode=disable"
    credentials_path: /mnt/db-credentials
  redis:
    addr: redis:6379
    read_timeout: 5s
    write_timeout: 5s
    pool_size: 10
publisher:
  order_publisher:
    topic_arn: "arn:aws:sns:ap-south-1:731315896571:OrderPublisher.fifo"
consumer:
  order_consumer:
    provider: sqs
    region: ap-south-1
    queue_url: https://sqs.ap-south-1.amazonaws.com/731315896571/order-service-queue.fifo
    raw_message: false
    wait_time: 30
