// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"github.com/go-kratos/kratos/v2"
	"github.com/go-kratos/kratos/v2/log"
	"order-service/internal/biz"
	"order-service/internal/conf"
	"order-service/internal/data"
	"order-service/internal/server"
	"order-service/internal/service"
)

import (
	_ "go.uber.org/automaxprocs"
)

// Injectors from wire.go:

// wireApp init kratos application.
func wireApp(confServer *conf.Server, confData *conf.Data, logger log.Logger) (*kratos.App, func(), error) {
	dataData, cleanup, err := data.NewData(confData, logger)
	if err != nil {
		return nil, nil, err
	}
	ordersRepository := data.NewOrdersRepository(dataData, logger)
	ordersHandlerInterface := biz.NewOrdersHandler(ordersRepository, logger)
	orderService := service.NewOrderService(ordersHandlerInterface)
	grpcServer := server.NewGRPCServer(confServer, orderService, logger)
	httpServer := server.NewHTTPServer(confServer, orderService, logger)
	app := newApp(logger, grpcServer, httpServer)
	return app, func() {
		cleanup()
	}, nil
}
